=== splattner/bfh_proj1_trafficlightsimulator/src/ch/bfh/proj1/trafficlightsimulator/TrafficLightConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema"
	xmlns:tns="http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema"
	elementFormDefault="qualified">

    <element name="TrafficLightConfig" type="tns:ConfigType"></element>

    <complexType name="ConfigType">
    	<sequence>
    		<element name="Junctions" type="tns:JunctionsType" maxOccurs="1" minOccurs="1"></element>
    		<element name="Streets" type="tns:StreetsType" maxOccurs="1" minOccurs="1"></element>
    		<element name="Lanes" type="tns:LanesType" maxOccurs="1" minOccurs="1"></element>
    		<element name="Routes" type="tns:RoutesType" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="JunctionType">
    	<sequence>
    		<element name="id" type="int" maxOccurs="1" minOccurs="1"></element>
            <element name="leftStreet" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="topStreet" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="rightStreet" type="int" maxOccurs="1" minOccurs="0"></element>
            <element name="bottomStreet" type="int" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="StreetType">
    	<sequence>
    		<element name="id" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="orientation" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="horizontal"></enumeration>
    					<enumeration value="vertical"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
            <element name="startJunction" type="int" maxOccurs="1" minOccurs="0">
    		</element>
            <element name="endJunction" type="int" maxOccurs="1" minOccurs="0">
    		</element>
        </sequence>
    </complexType>

    <complexType name="LaneType">
        <sequence>
        	<element name="id" type="int" maxOccurs="1" minOccurs="1"></element>
        	<element name="street" type="int" maxOccurs="1"
        		minOccurs="1">
        	</element>
        	<element name="direction" maxOccurs="1" minOccurs="1">
        		<simpleType>
        			<restriction base="string">
        				<enumeration value="endToStart"></enumeration>
        				<enumeration value="startToEnd"></enumeration>
        			</restriction>
        		</simpleType>
        	</element>
        </sequence>
    </complexType>

    <complexType name="RouteType">
        <sequence>
        	<element name="id" type="int" maxOccurs="1" minOccurs="1"></element>
        	<element name="lane" type="int" maxOccurs="unbounded" minOccurs="2"></element>
        </sequence>
    </complexType>


    <complexType name="JunctionsType">
    	<sequence>
    		<element name="junction" type="tns:JunctionType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="StreetsType">
    	<sequence>
    		<element name="street" type="tns:StreetType" maxOccurs="unbounded" minOccurs="2"></element>
    	</sequence>
    </complexType>
    
    <complexType name="LanesType">
    	<sequence>
    		<element name="lane" type="tns:LaneType" maxOccurs="unbounded" minOccurs="2"></element>
    	</sequence>
    </complexType>

    <complexType name="RoutesType">
    	<sequence>
    		<element name="route" type="tns:RouteType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

</schema>

=== splattner/bfh_proj1_trafficlightsimulator/TrafficLightsConfig2.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:TrafficLightConfig
	xmlns:tns="http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bfh.ch/project1/2014/I2R/TrafficLightConfigSchema bin/ch/bfh/proj1/trafficlightsimulator/TrafficLightConfigSchema.xsd ">

	<tns:Junctions>
		<tns:junction>
			<tns:id>1</tns:id>
			<tns:leftStreet>1</tns:leftStreet>
			<tns:topStreet>2</tns:topStreet>
			<tns:rightStreet>3</tns:rightStreet>
			<tns:bottomStreet>4</tns:bottomStreet>
		</tns:junction>
	</tns:Junctions>

	<tns:Streets>
		<tns:street>
			<tns:id>1</tns:id>
			<tns:orientation>horizontal</tns:orientation>
			<tns:endJunction>1</tns:endJunction>
		</tns:street>
		<tns:street>
			<tns:id>2</tns:id>
			<tns:orientation>vertical</tns:orientation>
			<tns:startJunction>1</tns:startJunction>
		</tns:street>
		<tns:street>
			<tns:id>3</tns:id>
			<tns:orientation>horizontal</tns:orientation>
			<tns:startJunction>1</tns:startJunction>
		</tns:street>
		<tns:street>
			<tns:id>4</tns:id>
			<tns:orientation>vertical</tns:orientation>
			<tns:endJunction>1</tns:endJunction>
		</tns:street>
	</tns:Streets>

	<tns:Lanes>
		<tns:lane>
			<tns:id>1</tns:id>
			<tns:street>1</tns:street>
			<tns:direction>endToStart</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>2</tns:id>
			<tns:street>1</tns:street>
			<tns:direction>startToEnd</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>3</tns:id>
			<tns:street>2</tns:street>
			<tns:direction>endToStart</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>4</tns:id>
			<tns:street>2</tns:street>
			<tns:direction>startToEnd</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>5</tns:id>
			<tns:street>3</tns:street>
			<tns:direction>endToStart</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>6</tns:id>
			<tns:street>3</tns:street>
			<tns:direction>startToEnd</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>7</tns:id>
			<tns:street>4</tns:street>
			<tns:direction>endToStart</tns:direction>
		</tns:lane>
		<tns:lane>
			<tns:id>8</tns:id>
			<tns:street>4</tns:street>
			<tns:direction>startToEnd</tns:direction>
		</tns:lane>
	</tns:Lanes>

	<tns:Routes>
		<tns:route>
			<tns:id>1</tns:id>
			<tns:lane>2</tns:lane>
			<tns:lane>4</tns:lane>
		</tns:route>
	</tns:Routes>

</tns:TrafficLightConfig>
